version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-spicyragdb}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data:/docker-entrypoint-initdb.d
    command: >
      bash -c "apt-get update &&
               apt-get install -y postgresql-15-pgvector &&
               docker-entrypoint.sh postgres"

  interface:
    build: .
    command: >
      sh -c "uvicorn interface.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    depends_on:
      - db

  streamlit:
    build: .
    command: >
      streamlit run streamlit/app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - interface

  mlflow:
    build: .
    ports:
      - "5001:5001"
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5001
      - BACKEND_STORE_URI=postgresql://${DB_USER:-user}:${DB_PASSWORD:-password}@db:5432/${DB_NAME:-spicyragdb}
    depends_on:
      - db
    command:
      -  mlflow server --backend-store-uri ${BACKEND_STORE_URI} --host 0.0.0.0 --port 5001
#

volumes:
  postgres_data:
