version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-spicyragdb}
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data:/docker-entrypoint-initdb.d
    command: >
      bash -c "apt-get update &&
               apt-get install -y postgresql-15-pgvector &&
               docker-entrypoint.sh postgres"

  interface_header:
    build: .
    command: >
      sh -c "
      until pg_isready -h db -p 5432; do
        echo 'Waiting for Postgres...'
        sleep 2
      done &&
      uvicorn interface.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8004:8000"
    depends_on:
      - db
    volumes:
      - ./interface:/app/interface

volumes:
  postgres_data:
