version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-spicyragdb}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  interface:
    build: .
    command: >
      sh -c "python load_data.py && uvicorn interface.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"

volumes:
  postgres_data:
