project:
  name: "SpicyRag"

database:
  user: "user"
  password: "password"
  name: "spicyragdb"

llm:
  base_url: "https://integrate.api.nvidia.com/v1"
  api_key: "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"
  model: "meta/llama-3.1-405b-instruct"
  role: "user"
  temperature: 0.2
  top_p: 0.7
  max_tokens: 1024
