project:
  name: "SpicyRag"

database:
  user: "user"
  password: "password"
  name: "spicyragdb"
  host: "localhost"
  port: 5432

logging:
  level: "INFO"

server:
  host: "0.0.0.0"
  port: 8000

llm:
  base_url: "${LLM_BASE_URL}"
  api_key: "${LLM_API_KEY}"
  model: "meta/llama-3.1-405b-instruct"
  role: "user"
  system_prompt: |
    Вы являетесь виртуальным юридическим консультантом, специализирующимся на анализе и интерпретации юридических документов и правовых норм.
    Ваша задача — помочь пользователю, используя предоставленный контекст, чтобы дать точный и обоснованный ответ на его юридический вопрос.
    Контекст может содержать выдержки из законов, нормативных актов, судебных решений, договоров или других юридических текстов.

    Инструкции:
      1. Внимательно проанализируй контекст и определите, какие части контекста наиболее релевантны, приводи всю полезную информацию из контекста
      2. Используй релевантные фрагменты контекста для создания полного и юридически обоснованного ответа. Приводи цитаты из контекста в соответствии. Но не пиши ничего про контекст
      3. Если в контексте есть числа (бюджет, выплаты, население, финансы), которое релевантно вопросы - ОБЯЗАТЕЛЬНО укажи эту статистику в ответе
      4. Если контекст совсем не соответствует вопросу, пиши: "Ответ на данный вопрос отсутствует в контексте."
    
    При ответе ни в коем случае не упоминай, что ты работаешь с контекстом. Так делать нельзя!!
    Отвечай структурно и по пунктам. Отвечай на русском языке!
  temperature: 0.15
  top_p: 0.7
  max_tokens: 8192

llm_respond:
  base_url: "${LLM_BASE_URL}"
  api_key: "${LLM_API_KEY}"
  model: "meta/llama-3.1-405b-instruct"
  role: "user"
  system_prompt: |
    Представь, что тебе задали следующий вопрос. Хотя точной информации по данному вопросу может не быть в доступных источниках, сгенерируй гипотетический ответ на основе твоих знаний. Затем используй этот ответ, чтобы найти релевантные данные или возможные факты, которые могут быть полезны для уточнения или подтверждения гипотезы.
    Сформулируй ответ, включая найденную информацию, если она есть, или гипотетические рассуждения, если точных данных нет.
    Отвечай только на русском языке. Отвечай одним абзацем
  temperature: 0.7
  top_p: 0.7
  max_tokens: 4096

embedding_model:
  batch_size: 16
  model_name: "deepvk/USER-base"
  model_type: ""
  embeddings_dir: "USER-base"
  dimension: 768
  prefix_query: "query: {}"
  prefix_document: "passage: {}"

elastic_params:
  host: "elasticsearch"
  port: 9200
  index_name: "chunks"

retrieval:
  vector_search_enabled: true
  similarity_threshold: 0.7
  top_k_vector: 3
  fulltext_search_enabled: true
  top_k_fulltext: 3
  top_k : 5

data_sources:
  excel_file: "./data/v2_ragas_npa_dataset_firstPart.xlsx"
  embeddings: "./data/embeddings"
  text_file: "./data/hmao_npa.txt"
  text_separator: "\n\n"

data_processing:
  chunker:
    py_class: interface.chunker.RecursiveCharacterTextSplitterChunker
    kwargs:
      chunk_size: 2048
      chunk_overlap: 256
      separators:
        - '\n#{1,6} '
        - '```\n'
        - '\n\\*\\*\\*+\n'
        - '\n---+\n'
        - '\n___+\n'
        - '\n\n'
        - '\n'
        - ' '
        - ''
        - ','
        - '|'
