project:
  name: "SpicyRag"

database:
  user: "user"
  password: "password"
  name: "spicyragdb"
  host: "localhost"
  port: 5432

logging:
  level: "INFO"

server:
  host: "0.0.0.0"
  port: 8000

llm:
  base_url: "https://integrate.api.nvidia.com/v1"
  api_key: "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"
  model: "meta/llama-3.1-405b-instruct"
  role: "user"
  temperature: 0.2
  top_p: 0.7
  max_tokens: 1024

embedding_model:
  name: "paraphrase-MiniLM-L6-v2"
  dimension: 384

data_sources:
  excel_file: "./data/v2_ragas_npa_dataset_firstPart.xlsx"
  text_file: "./data/hmao_npa.txt"
  text_separator: "\n\n"

data_processing:
  chunk_size: 2048
  top_k: 3
  similarity_threshold: 0.7